### ISSUE TITLE
Add HTTPS to the site

### ISSUE THREAD

**Issue by jaaynus** [torontocrypto/torontocrypto.github.io#9]
This can be accomplished by placing a proxy in the middle or forcing a redirect to a static HTTPS.

Reference:
https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

**Comment by jaaynus** [comment]
This can be possible by using Cloudflare's free SSL service. As per the reference above, the connection is encrypted user -> cloudflare but NOT ENCRYPTED cloudflare -> github. While this isn't the most optimal situation, it'll still protect our users.

**Comment by dmix** [comment]
If you point the site back to CF I can add the HTTPS stuff. It's already set up, I'll just add a CNAME to torontocrypto.github.io. Since github.io has HTTPS the connection between CF<>tc.github.io should be using SSL as well. So that might not be an issue.

**Comment by jaaynus** [comment]
Dan,

What's the nameservers for CF?

Regards,

**Comment by dmix** [comment]
Done, added via CF https://torontocrypto.org
